ALTER TABLE provider_requests ADD COLUMN provider TEXT;
ALTER TABLE provider_requests ADD COLUMN protocol TEXT;
ALTER TABLE provider_requests ADD COLUMN parser_version INTEGER CHECK(parser_version >= 0);
ALTER TABLE provider_requests ADD COLUMN observation_status TEXT;
ALTER TABLE provider_requests ADD COLUMN model TEXT;
ALTER TABLE provider_requests ADD COLUMN stream INTEGER CHECK(stream IN (0, 1));
ALTER TABLE provider_requests ADD COLUMN background INTEGER CHECK(background IN (0, 1));
ALTER TABLE provider_requests ADD COLUMN store INTEGER CHECK(store IN (0, 1));
ALTER TABLE provider_requests ADD COLUMN reasoning_effort TEXT;
ALTER TABLE provider_requests ADD COLUMN text_verbosity TEXT;
ALTER TABLE provider_requests ADD COLUMN truncation TEXT;
ALTER TABLE provider_requests ADD COLUMN previous_response_id_present INTEGER CHECK(previous_response_id_present IN (0, 1));
ALTER TABLE provider_requests ADD COLUMN input_item_count INTEGER CHECK(input_item_count >= 0);
ALTER TABLE provider_requests ADD COLUMN tool_count INTEGER CHECK(tool_count >= 0);
ALTER TABLE provider_requests ADD COLUMN text_input_block_count INTEGER CHECK(text_input_block_count >= 0);
ALTER TABLE provider_requests ADD COLUMN image_input_block_count INTEGER CHECK(image_input_block_count >= 0);
ALTER TABLE provider_requests ADD COLUMN file_input_block_count INTEGER CHECK(file_input_block_count >= 0);

ALTER TABLE provider_attempts ADD COLUMN provider_response_id TEXT;
ALTER TABLE provider_attempts ADD COLUMN response_model TEXT;
ALTER TABLE provider_attempts ADD COLUMN response_state TEXT;
ALTER TABLE provider_attempts ADD COLUMN provider_created_at TEXT;
ALTER TABLE provider_attempts ADD COLUMN incomplete_reason TEXT;
ALTER TABLE provider_attempts ADD COLUMN error_code TEXT;
ALTER TABLE provider_attempts ADD COLUMN transport_error TEXT;
ALTER TABLE provider_attempts ADD COLUMN observation_status TEXT;
ALTER TABLE provider_attempts ADD COLUMN streaming INTEGER CHECK(streaming IN (0, 1));
ALTER TABLE provider_attempts ADD COLUMN chunk_count INTEGER CHECK(chunk_count >= 0);
ALTER TABLE provider_attempts ADD COLUMN byte_count INTEGER CHECK(byte_count >= 0);
ALTER TABLE provider_attempts ADD COLUMN ttfb_us INTEGER CHECK(ttfb_us >= 0);
ALTER TABLE provider_attempts ADD COLUMN ttft_us INTEGER CHECK(ttft_us >= 0);
ALTER TABLE provider_attempts ADD COLUMN duration_us INTEGER CHECK(duration_us >= 0);
ALTER TABLE provider_attempts ADD COLUMN anomaly_metadata TEXT CHECK(length(anomaly_metadata) <= 4096);

ALTER TABLE provider_usage ADD COLUMN raw_usage_json BLOB CHECK(length(raw_usage_json) <= 65536);
ALTER TABLE provider_usage ADD COLUMN input_cached INTEGER CHECK(input_cached >= 0);
ALTER TABLE provider_usage ADD COLUMN output_reasoning INTEGER CHECK(output_reasoning >= 0);
ALTER TABLE provider_usage ADD COLUMN total INTEGER CHECK(total >= 0);
ALTER TABLE provider_usage ADD COLUMN normalizer_version INTEGER CHECK(normalizer_version >= 0);
ALTER TABLE provider_usage ADD COLUMN anomaly_metadata TEXT CHECK(length(anomaly_metadata) <= 4096);
