CREATE TABLE context_snapshots (
    snapshot_id TEXT NOT NULL PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id),
    provider_request_id TEXT NOT NULL REFERENCES provider_requests(request_id),
    inference_operation_id TEXT NOT NULL REFERENCES operations(operation_id),
    analysis_version INTEGER NOT NULL CHECK(analysis_version >= 0),
    status TEXT NOT NULL,
    started_at_us INTEGER NOT NULL CHECK(started_at_us >= 0),
    completed_at_us INTEGER CHECK(completed_at_us >= 0),
    recovered_at_us INTEGER CHECK(recovered_at_us >= 0),
    request_content_hash BLOB CHECK(length(request_content_hash) = 32),
    explicit_block_count INTEGER CHECK(explicit_block_count >= 0),
    analyzed_bytes INTEGER CHECK(analyzed_bytes >= 0),
    skipped_bytes INTEGER CHECK(skipped_bytes >= 0),
    explicit_request_complete INTEGER CHECK(explicit_request_complete IN (0, 1)),
    uses_previous_response INTEGER CHECK(uses_previous_response IN (0, 1)),
    uses_conversation_state INTEGER CHECK(uses_conversation_state IN (0, 1)),
    uses_item_references INTEGER CHECK(uses_item_references IN (0, 1)),
    uses_prompt_reference INTEGER CHECK(uses_prompt_reference IN (0, 1)),
    uses_external_files INTEGER CHECK(uses_external_files IN (0, 1)),
    uses_external_images INTEGER CHECK(uses_external_images IN (0, 1)),
    contains_opaque_items INTEGER CHECK(contains_opaque_items IN (0, 1)),
    logical_context_status TEXT,
    duplicate_key_detected INTEGER CHECK(duplicate_key_detected IN (0, 1)),
    reference_resolved_locally INTEGER CHECK(reference_resolved_locally IN (0, 1)),
    correlation_status TEXT,
    UNIQUE(provider_request_id, analysis_version)
) STRICT;

CREATE INDEX context_snapshots_session_idx ON context_snapshots(session_id, snapshot_id);

CREATE TABLE context_block_occurrences (
    block_occurrence_id TEXT NOT NULL PRIMARY KEY,
    snapshot_id TEXT NOT NULL REFERENCES context_snapshots(snapshot_id),
    ordinal INTEGER NOT NULL CHECK(ordinal >= 0),
    parent_block_occurrence_id TEXT REFERENCES context_block_occurrences(block_occurrence_id),
    kind TEXT NOT NULL,
    role TEXT NOT NULL,
    origin TEXT NOT NULL,
    semantic_path TEXT CHECK(length(semantic_path) <= 256),
    semantic_path_truncated INTEGER CHECK(semantic_path_truncated IN (0, 1)),
    semantic_path_hash BLOB CHECK(length(semantic_path_hash) = 32),
    raw_value_start INTEGER NOT NULL CHECK(raw_value_start >= 0),
    raw_value_end INTEGER NOT NULL CHECK(raw_value_end >= raw_value_start),
    locator_occurrence INTEGER NOT NULL CHECK(locator_occurrence >= 0),
    raw_bytes INTEGER NOT NULL CHECK(raw_bytes >= 0),
    exact_fingerprint BLOB CHECK(length(exact_fingerprint) = 32),
    semantic_fingerprint BLOB CHECK(length(semantic_fingerprint) = 32),
    fingerprint_version INTEGER CHECK(fingerprint_version >= 0),
    estimated_tokens INTEGER CHECK(estimated_tokens >= 0),
    estimator TEXT CHECK(length(estimator) <= 64),
    estimator_version INTEGER CHECK(estimator_version >= 0),
    estimator_encoding TEXT CHECK(length(estimator_encoding) <= 64),
    estimate_confidence TEXT,
    detected_kind TEXT,
    detector_confidence REAL CHECK(detector_confidence BETWEEN 0.0 AND 1.0),
    detector_version INTEGER CHECK(detector_version >= 0),
    tool_call_id TEXT CHECK(length(tool_call_id) <= 128),
    tool_name TEXT CHECK(length(tool_name) <= 128),
    tool_name_truncated INTEGER CHECK(tool_name_truncated IN (0, 1)),
    tool_name_hash BLOB CHECK(length(tool_name_hash) = 32),
    line_count INTEGER CHECK(line_count >= 0),
    max_line_length INTEGER CHECK(max_line_length >= 0),
    duplicate_line_ratio REAL CHECK(duplicate_line_ratio BETWEEN 0.0 AND 1.0),
    unique_line_ratio REAL CHECK(unique_line_ratio BETWEEN 0.0 AND 1.0),
    json_item_count INTEGER CHECK(json_item_count >= 0),
    json_depth INTEGER CHECK(json_depth >= 0),
    error_line_density REAL CHECK(error_line_density BETWEEN 0.0 AND 1.0),
    warning_line_density REAL CHECK(warning_line_density BETWEEN 0.0 AND 1.0),
    repetition_score REAL CHECK(repetition_score BETWEEN 0.0 AND 1.0),
    opportunity_signals TEXT CHECK(length(opportunity_signals) <= 256),
    candidate_estimated_tokens INTEGER CHECK(candidate_estimated_tokens >= 0),
    UNIQUE(snapshot_id, ordinal),
    CHECK(parent_block_occurrence_id IS NULL OR parent_block_occurrence_id <> block_occurrence_id)
) STRICT;

CREATE INDEX context_block_occurrences_exact_fingerprint_idx
    ON context_block_occurrences(exact_fingerprint);

CREATE INDEX context_block_occurrences_semantic_fingerprint_idx
    ON context_block_occurrences(semantic_fingerprint);

CREATE TABLE context_analysis_metrics (
    snapshot_id TEXT NOT NULL PRIMARY KEY REFERENCES context_snapshots(snapshot_id),
    explicit_bytes INTEGER CHECK(explicit_bytes >= 0),
    estimated_tokens_kind_instructions INTEGER CHECK(estimated_tokens_kind_instructions >= 0),
    estimated_tokens_kind_message INTEGER CHECK(estimated_tokens_kind_message >= 0),
    estimated_tokens_kind_text INTEGER CHECK(estimated_tokens_kind_text >= 0),
    estimated_tokens_kind_image_reference INTEGER CHECK(estimated_tokens_kind_image_reference >= 0),
    estimated_tokens_kind_file_reference INTEGER CHECK(estimated_tokens_kind_file_reference >= 0),
    estimated_tokens_kind_tool_definition INTEGER CHECK(estimated_tokens_kind_tool_definition >= 0),
    estimated_tokens_kind_tool_call INTEGER CHECK(estimated_tokens_kind_tool_call >= 0),
    estimated_tokens_kind_tool_result INTEGER CHECK(estimated_tokens_kind_tool_result >= 0),
    estimated_tokens_kind_item_reference INTEGER CHECK(estimated_tokens_kind_item_reference >= 0),
    estimated_tokens_kind_prompt_reference INTEGER CHECK(estimated_tokens_kind_prompt_reference >= 0),
    estimated_tokens_kind_provider_state_reference INTEGER CHECK(estimated_tokens_kind_provider_state_reference >= 0),
    estimated_tokens_kind_assistant_history INTEGER CHECK(estimated_tokens_kind_assistant_history >= 0),
    estimated_tokens_kind_opaque_reasoning INTEGER CHECK(estimated_tokens_kind_opaque_reasoning >= 0),
    estimated_tokens_kind_opaque INTEGER CHECK(estimated_tokens_kind_opaque >= 0),
    estimated_tokens_kind_unknown INTEGER CHECK(estimated_tokens_kind_unknown >= 0),
    estimated_tokens_role_system INTEGER CHECK(estimated_tokens_role_system >= 0),
    estimated_tokens_role_developer INTEGER CHECK(estimated_tokens_role_developer >= 0),
    estimated_tokens_role_user INTEGER CHECK(estimated_tokens_role_user >= 0),
    estimated_tokens_role_assistant INTEGER CHECK(estimated_tokens_role_assistant >= 0),
    estimated_tokens_role_tool INTEGER CHECK(estimated_tokens_role_tool >= 0),
    estimated_tokens_role_unknown INTEGER CHECK(estimated_tokens_role_unknown >= 0),
    estimated_tokens_origin_human_authored INTEGER CHECK(estimated_tokens_origin_human_authored >= 0),
    estimated_tokens_origin_agent_generated INTEGER CHECK(estimated_tokens_origin_agent_generated >= 0),
    estimated_tokens_origin_tool_generated INTEGER CHECK(estimated_tokens_origin_tool_generated >= 0),
    estimated_tokens_origin_tool_schema INTEGER CHECK(estimated_tokens_origin_tool_schema >= 0),
    estimated_tokens_origin_provider_managed INTEGER CHECK(estimated_tokens_origin_provider_managed >= 0),
    estimated_tokens_origin_external_reference INTEGER CHECK(estimated_tokens_origin_external_reference >= 0),
    estimated_tokens_origin_tracepress_generated INTEGER CHECK(estimated_tokens_origin_tracepress_generated >= 0),
    estimated_tokens_origin_unknown INTEGER CHECK(estimated_tokens_origin_unknown >= 0),
    estimated_tool_definition_share REAL CHECK(estimated_tool_definition_share BETWEEN 0.0 AND 1.0),
    estimated_tool_result_share REAL CHECK(estimated_tool_result_share BETWEEN 0.0 AND 1.0),
    estimated_human_text_share REAL CHECK(estimated_human_text_share BETWEEN 0.0 AND 1.0),
    estimated_assistant_history_share REAL CHECK(estimated_assistant_history_share BETWEEN 0.0 AND 1.0),
    estimated_unique_content_share REAL CHECK(estimated_unique_content_share BETWEEN 0.0 AND 1.0),
    estimated_repeated_content_share REAL CHECK(estimated_repeated_content_share BETWEEN 0.0 AND 1.0),
    tool_count INTEGER CHECK(tool_count >= 0),
    schema_bytes INTEGER CHECK(schema_bytes >= 0),
    estimated_schema_tokens INTEGER CHECK(estimated_schema_tokens >= 0),
    largest_tool_schema INTEGER CHECK(largest_tool_schema >= 0),
    repeated_schema_tokens INTEGER CHECK(repeated_schema_tokens >= 0),
    stable_explicit_prefix_estimate INTEGER CHECK(stable_explicit_prefix_estimate >= 0),
    estimator TEXT CHECK(length(estimator) <= 64),
    estimator_version INTEGER CHECK(estimator_version >= 0),
    estimate_confidence TEXT,
    opportunity_signals TEXT CHECK(length(opportunity_signals) <= 256)
) STRICT;

CREATE TABLE context_deltas (
    current_snapshot_id TEXT NOT NULL PRIMARY KEY REFERENCES context_snapshots(snapshot_id),
    previous_snapshot_id TEXT NOT NULL REFERENCES context_snapshots(snapshot_id),
    repeated_blocks INTEGER CHECK(repeated_blocks >= 0),
    new_blocks INTEGER CHECK(new_blocks >= 0),
    changed_blocks INTEGER CHECK(changed_blocks >= 0),
    removed_blocks INTEGER CHECK(removed_blocks >= 0),
    repeated_estimated_tokens INTEGER CHECK(repeated_estimated_tokens >= 0),
    new_estimated_tokens INTEGER CHECK(new_estimated_tokens >= 0),
    common_prefix_blocks INTEGER CHECK(common_prefix_blocks >= 0),
    common_prefix_estimated_tokens INTEGER CHECK(common_prefix_estimated_tokens >= 0),
    CHECK(previous_snapshot_id <> current_snapshot_id)
) STRICT;

CREATE TABLE token_reconciliations (
    snapshot_id TEXT NOT NULL PRIMARY KEY REFERENCES context_snapshots(snapshot_id),
    attempt_id TEXT REFERENCES provider_usage(attempt_id),
    visible_estimated_tokens INTEGER CHECK(visible_estimated_tokens >= 0),
    provider_input_tokens INTEGER CHECK(provider_input_tokens >= 0),
    residual_tokens INTEGER,
    comparability TEXT NOT NULL
) STRICT;
